spring.application.name=concorrencia-bancaria

# console no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# banco de dados em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# mostrar sql's no terminal do vs code
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring criar as tabelas automaticamente e adiar a inserção dos dados pra depois de criar as tabelas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true